/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HouseholdInverterBatteriesRouteImport } from './routes/household-inverter-batteries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarBatteriesRouteImport } from './routes/car-batteries'
import { Route as BikeBatteriesRouteImport } from './routes/bike-batteries'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdInverterBatteriesRoute =
  HouseholdInverterBatteriesRouteImport.update({
    id: '/household-inverter-batteries',
    path: '/household-inverter-batteries',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarBatteriesRoute = CarBatteriesRouteImport.update({
  id: '/car-batteries',
  path: '/car-batteries',
  getParentRoute: () => rootRouteImport,
} as any)
const BikeBatteriesRoute = BikeBatteriesRouteImport.update({
  id: '/bike-batteries',
  path: '/bike-batteries',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bike-batteries': typeof BikeBatteriesRoute
  '/car-batteries': typeof CarBatteriesRoute
  '/contact': typeof ContactRoute
  '/household-inverter-batteries': typeof HouseholdInverterBatteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bike-batteries': typeof BikeBatteriesRoute
  '/car-batteries': typeof CarBatteriesRoute
  '/contact': typeof ContactRoute
  '/household-inverter-batteries': typeof HouseholdInverterBatteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bike-batteries': typeof BikeBatteriesRoute
  '/car-batteries': typeof CarBatteriesRoute
  '/contact': typeof ContactRoute
  '/household-inverter-batteries': typeof HouseholdInverterBatteriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-choose-us': typeof WhyChooseUsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bike-batteries'
    | '/car-batteries'
    | '/contact'
    | '/household-inverter-batteries'
    | '/sitemap.xml'
    | '/why-choose-us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bike-batteries'
    | '/car-batteries'
    | '/contact'
    | '/household-inverter-batteries'
    | '/sitemap.xml'
    | '/why-choose-us'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bike-batteries'
    | '/car-batteries'
    | '/contact'
    | '/household-inverter-batteries'
    | '/sitemap.xml'
    | '/why-choose-us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BikeBatteriesRoute: typeof BikeBatteriesRoute
  CarBatteriesRoute: typeof CarBatteriesRoute
  ContactRoute: typeof ContactRoute
  HouseholdInverterBatteriesRoute: typeof HouseholdInverterBatteriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household-inverter-batteries': {
      id: '/household-inverter-batteries'
      path: '/household-inverter-batteries'
      fullPath: '/household-inverter-batteries'
      preLoaderRoute: typeof HouseholdInverterBatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-batteries': {
      id: '/car-batteries'
      path: '/car-batteries'
      fullPath: '/car-batteries'
      preLoaderRoute: typeof CarBatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bike-batteries': {
      id: '/bike-batteries'
      path: '/bike-batteries'
      fullPath: '/bike-batteries'
      preLoaderRoute: typeof BikeBatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BikeBatteriesRoute: BikeBatteriesRoute,
  CarBatteriesRoute: CarBatteriesRoute,
  ContactRoute: ContactRoute,
  HouseholdInverterBatteriesRoute: HouseholdInverterBatteriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
